# Generated by Django 5.1 on 2024-08-14 02:41

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=markdownx.models.MarkdownxField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Desciption'),
        ),
    ]
