# Generated by Django 5.1 on 2024-08-24 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image_course_syllabus_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='join_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Join URL'),
        ),
        migrations.AddField(
            model_name='course',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Platform'),
        ),
    ]
