# Generated by Django 5.1 on 2024-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name': 'Studen',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
