# Generated by Django 5.1 on 2024-08-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.FileField(upload_to='syllabus/', verbose_name='Syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('description', models.TextField(verbose_name='Course Description')),
                ('syllabu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.syllabus', verbose_name='Sylabus')),
            ],
        ),
    ]
