# Generated by Django 5.1 on 2024-08-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='courses.course', verbose_name='Courses')),
                ('students', models.ManyToManyField(to='student.student', verbose_name='Students')),
                ('teachers', models.ManyToManyField(to='teacher.teacher', verbose_name='Teachers')),
            ],
        ),
    ]
