# Generated by Django 5.1 on 2024-08-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='Firts Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('username', models.TextField(verbose_name='User Name')),
                ('password', models.TextField(verbose_name='Password')),
            ],
        ),
    ]
